/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type BadgeItem = {
  _type: "badgeItem";
  name?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  position?: string;
  company?: string;
  quote?: string;
  avatar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  companyLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ClientLogo = {
  _id: string;
  _type: "clientLogo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: "Business strategies" | "Digital marketing" | "E-commerce" | "Media production" | "Live streaming" | "Event organization" | "Design" | "Influencer management";
  description?: string;
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  whyTitle?: string;
  benefitImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  benefits?: Array<string>;
  portfolios?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "work";
  }>;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  eyebrow?: string;
  subtitle?: string;
  productCategory?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "productCategory";
  };
  longDescription?: string;
  thumbnail?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  motionVideo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  certifications?: Array<{
    _key: string;
  } & BadgeItem>;
  awards?: Array<{
    _key: string;
  } & BadgeItem>;
  isFeatured?: boolean;
  seo?: Seo;
};

export type ProductCategory = {
  _id: string;
  _type: "productCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Work = {
  _id: string;
  _type: "work";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  client?: string;
  year?: string;
  tags?: Array<string>;
  shortDesc?: string;
  description?: string;
  thumbnail?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroMedia?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  beforeAfter?: {
    before?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    after?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  stickySections?: Array<{
    title?: string;
    content?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  metrics?: Array<{
    value?: string;
    label?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = BadgeItem | SiteSettings | Seo | Testimonial | SanityImageCrop | SanityImageHotspot | ClientLogo | Service | Slug | Product | ProductCategory | Work | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/components/home/ClientSection.tsx
// Variable: CLIENTS_QUERY
// Query: *[_type == "clientLogo"] | order(_createdAt desc) {  _id,  name,  "logo": logo.asset->url}
export type CLIENTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  logo: string | null;
}>;

// Source: ./app/components/home/ProductsSection.tsx
// Variable: PRODUCTS_HOME_QUERY
// Query: *[_type == "product"] | order(coalesce(isFeatured, false) desc, _updatedAt desc)[0...3] {  title,  "slug": slug.current,  subtitle,  longDescription,  thumbnail,  isFeatured}
export type PRODUCTS_HOME_QUERYResult = Array<{
  title: string | null;
  slug: string | null;
  subtitle: string | null;
  longDescription: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  isFeatured: boolean | null;
}>;

// Source: ./app/components/home/ServiceSection.tsx
// Variable: SERVICE_CARDS_QUERY
// Query: [  *[_type == "service" && category == "Business strategies"] | order(_createdAt asc)[0],  *[_type == "service" && category == "E-commerce"] | order(_createdAt asc)[0],  *[_type == "service" && category == "Digital marketing"] | order(_createdAt asc)[0]] {  title,  description,  category,  "slug": slug.current,  "image": heroImage.asset->url}
export type SERVICE_CARDS_QUERYResult = Array<{
  title: string | null;
  description: string | null;
  category: "Business strategies";
  slug: string | null;
  image: string | null;
} | null | {
  title: string | null;
  description: string | null;
  category: "Digital marketing";
  slug: string | null;
  image: string | null;
} | {
  title: string | null;
  description: string | null;
  category: "E-commerce";
  slug: string | null;
  image: string | null;
}>;

// Source: ./app/components/home/TestimonialSection.tsx
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(_createdAt desc)[0...10] {  name,  position,  company,  quote,  "avatar": avatar.asset->url,  "companyLogo": companyLogo.asset->url}
export type TESTIMONIALS_QUERYResult = Array<{
  name: string | null;
  position: string | null;
  company: string | null;
  quote: string | null;
  avatar: string | null;
  companyLogo: string | null;
}>;

// Source: ./app/components/home/WorksSection.tsx
// Variable: WORKS_HOME_QUERY
// Query: *[_type == "work"] | order(_createdAt desc)[0...4] {  title,  "slug": slug.current,  client,  year,  "thumbnail": thumbnail.asset->url}
export type WORKS_HOME_QUERYResult = Array<{
  title: string | null;
  slug: string | null;
  client: string | null;
  year: string | null;
  thumbnail: string | null;
}>;

// Source: ./app/layout.tsx
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {  siteTitle,  seo {    metaTitle,    metaDescription  }}
export type SITE_SETTINGS_QUERYResult = {
  siteTitle: string | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
  } | null;
} | null;
// Variable: SERVICES_NAV_QUERY
// Query: *[_type == "service"] | order(title asc) {  title,  "slug": slug.current,  category}
export type SERVICES_NAV_QUERYResult = Array<{
  title: string | null;
  slug: string | null;
  category: "Business strategies" | "Design" | "Digital marketing" | "E-commerce" | "Event organization" | "Influencer management" | "Live streaming" | "Media production" | null;
}>;

// Source: ./app/lib/seoHelper.ts
// Variable: SEO_QUERY
// Query: *[_type == $type && slug.current == $slug][0] { title, seo }
export type SEO_QUERYResult = {
  title: null;
  seo: null;
} | {
  title: string | null;
  seo: null;
} | {
  title: null;
  seo: Seo | null;
} | {
  title: string | null;
  seo: Seo | null;
} | null;

// Source: ./app/products/[slug]/page.tsx
// Variable: PRODUCT_QUERY
// Query: *[_type == "product" && slug.current == $slug][0] {  ...,  "category": coalesce(productCategory->title, category),  "categorySlug": productCategory->slug.current,  "motionVideoUrl": motionVideo.asset->url,  "heroImageAspectRatio": heroImage.asset->metadata.dimensions.aspectRatio,}
export type PRODUCT_QUERYResult = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  eyebrow?: string;
  subtitle?: string;
  productCategory?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "productCategory";
  };
  longDescription?: string;
  thumbnail?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  motionVideo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  certifications?: Array<{
    _key: string;
  } & BadgeItem>;
  awards?: Array<{
    _key: string;
  } & BadgeItem>;
  isFeatured?: boolean;
  seo?: Seo;
  category: string | null;
  categorySlug: string | null;
  motionVideoUrl: string | null;
  heroImageAspectRatio: number | null;
} | null;
// Variable: RELATED_PRODUCTS_QUERY
// Query: *[_type == "product" && slug.current != $slug && productCategory->slug.current == $categorySlug] | order(_createdAt desc)[0...3] {  title,  "slug": slug.current,  "category": coalesce(productCategory->title, category),  thumbnail}
export type RELATED_PRODUCTS_QUERYResult = Array<{
  title: string | null;
  slug: string | null;
  category: string | null;
  thumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;
// Variable: PRODUCT_SLUGS_QUERY
// Query: *[_type == "product"] { "slug": slug.current }
export type PRODUCT_SLUGS_QUERYResult = Array<{
  slug: string | null;
}>;

// Source: ./app/products/category/[slug]/page.tsx
// Variable: CATEGORY_PAGE_QUERY
// Query: *[_type == "productCategory" && slug.current == $slug][0]{  _id,  title,  "slug": slug.current,  description,  coverImage,  "coverImageAspectRatio": coverImage.asset->metadata.dimensions.aspectRatio,  "products": *[_type == "product" && references(^._id)] | order(_updatedAt desc) {    _id,    title,    "slug": slug.current,    eyebrow,    subtitle,    longDescription,    thumbnail,    "category": coalesce(productCategory->title, category),    "categorySlug": productCategory->slug.current  }}
export type CATEGORY_PAGE_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  coverImageAspectRatio: number | null;
  products: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    eyebrow: string | null;
    subtitle: string | null;
    longDescription: string | null;
    thumbnail: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    category: string | null;
    categorySlug: string | null;
  }>;
} | null;
// Variable: CATEGORY_SLUGS_QUERY
// Query: *[_type == "productCategory" && defined(slug.current)]{  "slug": slug.current}
export type CATEGORY_SLUGS_QUERYResult = Array<{
  slug: string | null;
}>;

// Source: ./app/products/page.tsx
// Variable: PRODUCT_CATEGORIES_QUERY
// Query: *[_type == "productCategory"] | order(title asc) {  _id,  title,  "slug": slug.current,  description,  coverImage,  "productCount": count(*[_type == "product" && references(^._id)])}
export type PRODUCT_CATEGORIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  productCount: number;
}>;

// Source: ./app/services/[slug]/page.tsx
// Variable: SERVICE_QUERY
// Query: *[_type == "service" && slug.current == $slug][0] {    title,    "slug": slug.current,    category,    description,    "heroImage": heroImage.asset->url,    whyTitle,    "benefitImage": benefitImage.asset->url,    benefits,    portfolios[]->{      _id,      title,      "slug": slug.current,      "image": thumbnail.asset->url    }  }
export type SERVICE_QUERYResult = {
  title: string | null;
  slug: string | null;
  category: "Business strategies" | "Design" | "Digital marketing" | "E-commerce" | "Event organization" | "Influencer management" | "Live streaming" | "Media production" | null;
  description: string | null;
  heroImage: string | null;
  whyTitle: string | null;
  benefitImage: string | null;
  benefits: Array<string> | null;
  portfolios: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    image: string | null;
  }> | null;
} | null;

// Source: ./app/works/[slug]/page.tsx
// Variable: WORK_DETAIL_QUERY
// Query: *[_type == "work" && slug.current == $slug][0] {  title,  "slug": slug.current,  client,  year,  shortDesc,  description,  "heroMedia": heroMedia.asset->url,  "heroAspectRatio": heroMedia.asset->metadata.dimensions.aspectRatio,  beforeAfter {    "before": before.asset->url,    "after": after.asset->url  },  stickySections[] {    title,    content,    "image": image.asset->url  },  "gallery": gallery[] {    "url": asset->url,    "aspectRatio": asset->metadata.dimensions.aspectRatio  },  metrics}
export type WORK_DETAIL_QUERYResult = {
  title: string | null;
  slug: string | null;
  client: string | null;
  year: string | null;
  shortDesc: string | null;
  description: string | null;
  heroMedia: string | null;
  heroAspectRatio: number | null;
  beforeAfter: {
    before: string | null;
    after: string | null;
  } | null;
  stickySections: Array<{
    title: string | null;
    content: string | null;
    image: string | null;
  }> | null;
  gallery: Array<{
    url: string | null;
    aspectRatio: number | null;
  }> | null;
  metrics: Array<{
    value?: string;
    label?: string;
    _key: string;
  }> | null;
} | null;

// Source: ./app/works/page.tsx
// Variable: WORKS_QUERY
// Query: *[_type == "work"] | order(_createdAt desc) {    title,    "slug": slug.current,    "thumbnail": thumbnail.asset->url,    tags,    client,    year,  }
export type WORKS_QUERYResult = Array<{
  title: string | null;
  slug: string | null;
  thumbnail: string | null;
  tags: Array<string> | null;
  client: string | null;
  year: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"clientLogo\"] | order(_createdAt desc) {\n  _id,\n  name,\n  \"logo\": logo.asset->url\n}": CLIENTS_QUERYResult;
    "*[_type == \"product\"] | order(coalesce(isFeatured, false) desc, _updatedAt desc)[0...3] {\n  title,\n  \"slug\": slug.current,\n  subtitle,\n  longDescription,\n  thumbnail,\n  isFeatured\n}": PRODUCTS_HOME_QUERYResult;
    "[\n  *[_type == \"service\" && category == \"Business strategies\"] | order(_createdAt asc)[0],\n  *[_type == \"service\" && category == \"E-commerce\"] | order(_createdAt asc)[0],\n  *[_type == \"service\" && category == \"Digital marketing\"] | order(_createdAt asc)[0]\n] {\n  title,\n  description,\n  category,\n  \"slug\": slug.current,\n  \"image\": heroImage.asset->url\n}": SERVICE_CARDS_QUERYResult;
    "*[_type == \"testimonial\"] | order(_createdAt desc)[0...10] {\n  name,\n  position,\n  company,\n  quote,\n  \"avatar\": avatar.asset->url,\n  \"companyLogo\": companyLogo.asset->url\n}": TESTIMONIALS_QUERYResult;
    "*[_type == \"work\"] | order(_createdAt desc)[0...4] {\n  title,\n  \"slug\": slug.current,\n  client,\n  year,\n  \"thumbnail\": thumbnail.asset->url\n}": WORKS_HOME_QUERYResult;
    "*[_type == \"siteSettings\"][0] {\n  siteTitle,\n  seo {\n    metaTitle,\n    metaDescription\n  }\n}": SITE_SETTINGS_QUERYResult;
    "*[_type == \"service\"] | order(title asc) {\n  title,\n  \"slug\": slug.current,\n  category\n}": SERVICES_NAV_QUERYResult;
    "*[_type == $type && slug.current == $slug][0] { title, seo }": SEO_QUERYResult;
    "*[_type == \"product\" && slug.current == $slug][0] {\n  ...,\n  \"category\": coalesce(productCategory->title, category),\n  \"categorySlug\": productCategory->slug.current,\n  \"motionVideoUrl\": motionVideo.asset->url,\n  \"heroImageAspectRatio\": heroImage.asset->metadata.dimensions.aspectRatio,\n}": PRODUCT_QUERYResult;
    "*[_type == \"product\" && slug.current != $slug && productCategory->slug.current == $categorySlug] | order(_createdAt desc)[0...3] {\n  title,\n  \"slug\": slug.current,\n  \"category\": coalesce(productCategory->title, category),\n  thumbnail\n}": RELATED_PRODUCTS_QUERYResult;
    "*[_type == \"product\"] { \"slug\": slug.current }": PRODUCT_SLUGS_QUERYResult;
    "*[_type == \"productCategory\" && slug.current == $slug][0]{\n  _id,\n  title,\n  \"slug\": slug.current,\n  description,\n  coverImage,\n  \"coverImageAspectRatio\": coverImage.asset->metadata.dimensions.aspectRatio,\n  \"products\": *[_type == \"product\" && references(^._id)] | order(_updatedAt desc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    eyebrow,\n    subtitle,\n    longDescription,\n    thumbnail,\n    \"category\": coalesce(productCategory->title, category),\n    \"categorySlug\": productCategory->slug.current\n  }\n}": CATEGORY_PAGE_QUERYResult;
    "*[_type == \"productCategory\" && defined(slug.current)]{\n  \"slug\": slug.current\n}": CATEGORY_SLUGS_QUERYResult;
    "*[_type == \"productCategory\"] | order(title asc) {\n  _id,\n  title,\n  \"slug\": slug.current,\n  description,\n  coverImage,\n  \"productCount\": count(*[_type == \"product\" && references(^._id)])\n}": PRODUCT_CATEGORIES_QUERYResult;
    "*[_type == \"service\" && slug.current == $slug][0] {\n    title,\n    \"slug\": slug.current,\n    category,\n    description,\n    \"heroImage\": heroImage.asset->url,\n    whyTitle,\n    \"benefitImage\": benefitImage.asset->url,\n    benefits,\n    portfolios[]->{\n      _id,\n      title,\n      \"slug\": slug.current,\n      \"image\": thumbnail.asset->url\n    }\n  }": SERVICE_QUERYResult;
    "*[_type == \"work\" && slug.current == $slug][0] {\n  title,\n  \"slug\": slug.current,\n  client,\n  year,\n  shortDesc,\n  description,\n  \"heroMedia\": heroMedia.asset->url,\n  \"heroAspectRatio\": heroMedia.asset->metadata.dimensions.aspectRatio,\n  beforeAfter {\n    \"before\": before.asset->url,\n    \"after\": after.asset->url\n  },\n  stickySections[] {\n    title,\n    content,\n    \"image\": image.asset->url\n  },\n  \"gallery\": gallery[] {\n    \"url\": asset->url,\n    \"aspectRatio\": asset->metadata.dimensions.aspectRatio\n  },\n  metrics\n}": WORK_DETAIL_QUERYResult;
    "*[_type == \"work\"] | order(_createdAt desc) {\n    title,\n    \"slug\": slug.current,\n    \"thumbnail\": thumbnail.asset->url,\n    tags,\n    client,\n    year,\n  }": WORKS_QUERYResult;
  }
}
